# Generated by Django 3.0.5 on 2020-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istuntoNumero', models.IntegerField()),
                ('vuosi', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
