# Generated by Django 3.0.5 on 2020-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0004_auto_20200510_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aanestys',
            old_name='otsikko',
            new_name='aanestysOtsikko',
        ),
        migrations.AddField(
            model_name='aanestys',
            name='kohtaOtsikko',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
