# Generated by Django 3.0.5 on 2020-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0005_auto_20200510_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanestys',
            name='aanestysValtiopaivaasia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
