# Generated by Django 3.0.5 on 2020-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0007_aanestys_aanestyspoytakirja'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanestys',
            name='aanestysAlkuaika',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
