# Generated by Django 3.0.5 on 2020-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0008_aanestys_aanestysalkuaika'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanestys',
            name='aanestysTulosEi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanestys',
            name='aanestysTulosJaa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
