# Generated by Django 3.0.5 on 2020-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0009_auto_20200510_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanestys',
            name='aanestysTulosPoissa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
