# Generated by Django 3.0.5 on 2020-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0010_aanestys_aanestystulospoissa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AanestysEdustaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanestysId', models.IntegerField()),
                ('edustajaId', models.IntegerField()),
                ('edustajaAanestys', models.CharField(max_length=7)),
                ('edustajaEtunimi', models.CharField(max_length=30)),
                ('edustajaSukunimi', models.CharField(max_length=50)),
            ],
        ),
    ]
