# Generated by Django 3.0.5 on 2020-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigSister', '0012_memberofparliament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanestysedustaja',
            name='edustajaAanestys',
            field=models.CharField(max_length=17),
        ),
    ]
